// Generated by CoffeeScript 1.8.0
(function() {
  this.document.addEventListener('DOMContentLoaded', function(event) {
    var gallery, _i, _len, _ref, _results;
    _ref = this.querySelectorAll('div.gallery');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      gallery = _ref[_i];
      _results.push(new Flickity(gallery, {
        wrapAround: true,
        autoPlay: true
      }));
    }
    return _results;
  });

}).call(this);

//# sourceMappingURL=script.js.map
