name: Deploy Site

on:
  push:
    branches:
    - master
  # Uncomment this to make the workflow manual
  #workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 20.6.1
    - name: NPM Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
